@startuml diagramme de classes 
class CarManager
CarManager --> CarRater
CarManager --> CarsFormatter
CarManager --> carRepository
carRepository --> Car
CarsFormatter -->carRepository
CarRater --> carRepository
@enduml
